# Variables para almacenar los valores extraídos
options_dict = {
    'add-host': 'extra_hosts',
    'cap_add': 'cap_add',
    'cap_drop': 'cap_drop',
    'cgroup_parent': 'cgroup_parent',
    'device': 'devices',
    'dns': 'dns',
    'dns_search': 'dns_search',
    'env_file': 'env_file',
    'expose': 'expose',
    'hostname': 'hostname',
    'label': 'labels',
    'link': 'links',
    'log-driver': 'logging/driver',
    'log-opt': 'logging/options',
    'entrypoint': 'entrypoint',
    'env': 'environment',
    'name': 'container_name',
    'network': 'network_mode',
    'net': 'network_mode',
    'pid': 'pid',
    'privileged': 'privileged',
    'publish': 'ports',
    'read-only': 'read_only',
    'restart': 'restart',
    'tmpfs': 'tmpfs',
    'ulimit': 'ulimits',
    'user': 'user',
    'volume': 'volumes',
    'v': 'volumes',
    'p': 'ports',
    'e': 'environment',
    'l': 'labels',
    'h': 'hostname',
    'u': 'user'
}

options = {
        "--add-host": "Add a custom host-to-IP mapping (host:ip)",
        "-a": "Attach to STDIN, STDOUT or STDERR",
        "--attach": "Attach to STDIN, STDOUT or STDERR",
        "--blkio-weight": "Block IO (relative weight), between 10 and 1000, or 0 to disable (default 0)",
        "--blkio-weight-device": "Block IO weight (relative device weight) (default [])",
        "--cap-add": "Add Linux capabilities",
        "--cap-drop": "Drop Linux capabilities",
        "--cgroup-parent": "Optional parent cgroup for the container",
        "--cgroupns": "Cgroup namespace to use (host|private)",
        "--cidfile": "Write the container ID to the file",
        "--cpu-period": "Limit CPU CFS (Completely Fair Scheduler) period",
        "--cpu-quota": "Limit CPU CFS (Completely Fair Scheduler) quota",
        "--cpu-rt-period": "Limit CPU real-time period in microseconds",
        "--cpu-rt-runtime": "Limit CPU real-time runtime in microseconds",
        "-c": "CPU shares (relative weight)",
        "--cpu-shares": "CPU shares (relative weight)",
        "--cpus": "Number of CPUs",
        "--cpuset-cpus": "CPUs in which to allow execution (0-3, 0,1)",
        "--cpuset-mems": "MEMs in which to allow execution (0-3, 0,1)",
        #"-d": "Run container in background and print container ID",
        "--detach-keys": "Override the key sequence for detaching a container",
        "--device": "Add a host device to the container",
        "--device-cgroup-rule": "Add a rule to the cgroup allowed devices list",
        "--device-read-bps": "Limit read rate (bytes per second) from a device (default [])",
        "--device-read-iops": "Limit read rate (IO per second) from a device (default [])",
        "--device-write-bps": "Limit write rate (bytes per second) to a device (default [])",
        "--device-write-iops": "Limit write rate (IO per second) to a device (default [])",
        "--disable-content-trust": "Skip image verification (default true)",
        "--dns": "Set custom DNS servers",
        "--dns-option": "Set DNS options",
        "--dns-search": "Set custom DNS search domains",
        "--domainname": "Container NIS domain name",
        "--entrypoint": "Overwrite the default ENTRYPOINT of the image",
        "-e": "Set environment variables",
        "--env-file": "Read in a file of environment variables",
        "--expose": "Expose a port or a range of ports",
        "--gpus": "GPU devices to add to the container ('all' to pass all GPUs)",
        "--group-add": "Add additional groups to join",
        "--health-cmd": "Command to run to check health",
        "--health-interval": "Time between running the check (ms|s|m|h) (default 0s)",
        "--health-retries": "Consecutive failures needed to report unhealthy",
        "--health-start-period": "Start period for the container to initialize before starting health-retries countdown (ms|s|m|h) (default 0s)",
        "--health-timeout": "Maximum time to allow one check to run (ms|s|m|h) (default 0s)",
        "--help": "Print usage",
        "-h": "Container host name",
        "--init": "Run an init inside the container",
        "-i": "Keep STDIN open even if not attached",
        "--ip": "IPv4 address (e.g., 172.30.100.104)",
        "--ip6": "IPv6 address (e.g., 2001:db8::33)",
        "--ipc": "IPC mode to use",
        "--isolation": "Container isolation technology",
        "--kernel-memory": "Kernel memory limit",
        "-l": "Set meta data on a container",
        "--label-file": "Read in a line delimited file of labels",
        "--link": "Add link to another container",
        "--link-local-ip": "Container IPv4/IPv6 link-local addresses",
        "--log-driver": "Logging driver for the container",
        "--log-opt": "Log driver options",
        "--mac-address": "Container MAC address (e.g., 92:d0:c6:0a:29:33)",
        "-m": "Memory limit",
        "--memory-reservation": "Memory soft limit",
        "--memory-swap": "Swap limit equal to memory plus swap: '-1' to enable unlimited swap",
        "--memory-swappiness": "Tune container memory swappiness (0 to 100) (default -1)",
        "--mount": "Attach a filesystem mount to the container",
        "--name": "Assign a name to the container",
        "--network": "Connect a container to a network",
        "--network-alias": "Add network-scoped alias for the container",
        "--no-healthcheck": "Disable any container-specified HEALTHCHECK",
        "--oom-kill-disable": "Disable OOM Killer",
        "--oom-score-adj": "Tune host's OOM preferences (-1000 to 1000)",
        "--pid": "PID namespace to use",
        "--pids-limit": "Tune container pids limit (set -1 for unlimited)",
        "--platform": "Set platform if server is multi-platform capable",
        "--privileged": "Give extended privileges to this container",
        "-p": "Publish a container's port(s) to the host",
        "-P": "Publish all exposed ports to random ports",
        "--pull": "Pull image before running ('always', 'missing', 'never') (default 'missing')",
        "-q": "Suppress the pull output",
        "--read-only": "Mount the container's root filesystem as read only",
        "--restart": "Restart policy to apply when a container exits (default 'no')",
        "--rm": "Automatically remove the container when it exits",
        "--runtime": "Runtime to use for this container",
        "--security-opt": "Security Options",
        "--shm-size": "Size of /dev/shm",
        "--sig-proxy": "Proxy received signals to the process (default true)",
        "--stop-signal": "Signal to stop the container",
        "--stop-timeout": "Timeout (in seconds) to stop a container",
        "--storage-opt": "Storage driver options for the container",
        "--sysctl": "Sysctl options (default map[])",
        "--tmpfs": "Mount a tmpfs directory",
        "-t": "Allocate a pseudo-TTY",
        "--ulimit": "Ulimit options (default [])",
        "-u": "Username or UID (format: <name|uid>[:<group|gid>])",
        "--userns": "User namespace to use",
        "--uts": "UTS namespace to use",
        "-v": "Bind mount a volume",
        "--volume-driver": "Optional volume driver for the container",
        "--volumes-from": "Mount volumes from the specified container(s)",
        "-w": "Working directory inside the container"
    }
